### ISSUE TITLE
The encryped file doesn't execute

### ISSUE THREAD

**Issue by TMQrX** [furjac/FG_Crypter#1]
I have tried many times but when FG crypter encrypted my file, this file will doesn't execute anymore. I have checked in process hacker 2, when I run the encrypted file by FG crypter, the encrypted file will terminate immediately.

**Comment by furjac** [comment]
Sorry for late reply ok i gave a cmd in usage i said to run it at last 
run this according to ur output and correct path
```
pyinstaller --noconfirm --onefile --console --name "Scantime-Crypted" --add-data "C:/Users/Administrator/PycharmProjects/FG_Crypter/obfuscated.exe;."  "C:/Users/Administrator/PycharmProjects/FG_Crypter/stub.py"
```
ok this will start make ur exe working
